apiVersion: v1
kind: Service
metadata:
  name: heavy-api
  labels:
    app: heavy-api
spec:
  type: LoadBalencer
  selector:
    app: heavy-api
  ports:
  - protocol: TCP
    port: 8086
    name: svc-port
    targetPort: api-port